janssenlima/confapi/confapi/urls.py
from django.conf.urls import patterns, url

from confapi import views

urlpatterns = patterns('',
    url(r'^healthcheck/$', views.healthcheck, name='healthcheck'),
    url(r'^$', views.index, name='index'),
    url(r'^configure/$', views.configure, name='configure'),
    url(r'^use/$', views.use, name='use'),
    url(r'^extras/$', views.extras, name='extras'),
    url(r'^help/$', views.help, name='help'),
    url(r'^api_functions$', views.api_functions, name='api_functions'),
)

janssenlima/confapi/zbx/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'zbx.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

#    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('confapi.urls', namespace="confapi")),
)

janssenlima/confapi/confapi/models.py
from django.db import models



class Confapi(models.Model):
	question = models.CharField(max_length=200)
	

janssenlima/confapi/confapi/views.py
# coding=utf-8
import os
import sys
import json
import re
import requests
import collections
import ast

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from confapi.models import Confapi
from pprint import pformat
from django.conf import settings


path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../exec/")
sys.path.append(path)

from dizzy_zabbix import Zabbix


class IndexView(generic.DetailView):
    model = Confapi
    template_name = 'confapi/index.html'


class ConfigureView(generic.DetailView):
    # model =
    template_name = 'confapi/configure.html'


class ExtrasView(generic.DetailView):
    # model =
    template_name = 'confapi/extras.html'


class UseView(generic.DetailView):
    # model =
    template_name = 'confapi/use.html'


def healthcheck(request):
    return HttpResponse("WORKING")

def index(request):
    return render(request, 'confapi/index.html')


def help(request):
    return HttpResponseRedirect(settings.ENDPOINT_DOC)
    # return render(request, 'confapi/configure.html')


def configure(request):
    return render(request, 'confapi/configure.html')


def extras(request):
    return render(request, 'confapi/index.html')


def use(request):
    endpoint_options = settings.ENDPOINT_OPTIONS

    if request.POST:
        function_params = {}
        access_params = {}
        for k, v in request.POST.items():
            if re.match('^z_', k):
                access_params[k] = v
            elif k != 'csrfmiddlewaretoken':
                if v:
                    if v[0] == '{':
                        function_params[k] = ast.literal_eval(v)
                    else:
                        function_params[k] = v
        function = 'globo.' + function_params.pop('function') if not re.search('^.+\..+$', function_params[
            'function']) else function_params.pop('function')
        https = access_params.get('z_https', False)
        if not re.match('^http', access_params['z_endpoint']):
            access_params['z_endpoint'] = 'https://' + access_params['z_endpoint'] if https else 'http://' + \
                                                                                                 access_params[
                                                                                                     'z_endpoint']
        # print function_params

        try:
            z = Zabbix(access_params['z_endpoint'], access_params['z_username'], access_params['z_password'])
        except Exception:
            return render(request, 'confapi/use.html', {'post': True, 'error': True,
                                                        'endpoint_options': endpoint_options,
                                                        'response': "Não foi possível logar na API. Verifique os parâmetros de login.",
                                                        'z_endpoint': access_params['z_endpoint'],
                                                        'z_username': access_params['z_username'],
                                                        'z_password': access_params['z_password'],
                                                        'access_params': pformat(access_params, indent=4, width=40, ),
                                                        'function_params': pformat(function_params, indent=4, width=20),
                                                        'https': https})

        # z = Zabbix (access_params['z_endpoint'], access_params['z_username'], access_params['z_password'])

        api_response = z.x(function, function_params)
        api_response_json = json.dumps(api_response)
        return render(request, 'confapi/use.html',
                      {'post': True, 'response': api_response_json, 'endpoint_options': endpoint_options,
                       'z_endpoint': access_params['z_endpoint'],
                       'z_username': access_params['z_username'], 'z_password': access_params['z_password'],
                       'access_params': pformat(access_params, indent=4, width=40, ),
                       'function_params': pformat(function_params, indent=4, width=20), 'https': https})
    else:
        return render(request, 'confapi/use.html', {'post': False, 'endpoint_options': endpoint_options})


def api_functions(request):
    '''
    json_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static/confapi/data/api_functions.json")
    data = open(json_path)
    response = json.load(data)
    data.close()
    '''
    black_methods = ['userlogin']

    https = request.GET['z_https']
    gbix_endpoint = request.GET['endpoint'] + '/api/methods'

    if https == 1:
        protocol = 'https://'
    elif https == 0:
        protocol = 'http://'
    else:
        protocol = 'http://'

    if not re.match('^http', gbix_endpoint):
        gbix_endpoint = protocol + gbix_endpoint

    code = requests.get(gbix_endpoint)
    code_json = code.json()

    confapi_methods = {}

    for method in code_json:
        confapi_methods[method['name']] = {}
        # print method['name']

        for group_params in method['parameter']['fields']:
            for parameter in method['parameter']['fields'][group_params]:
                if not re.match('\w+\.\w+', parameter['field']):
                    confapi_methods[method['name']][parameter['field']] = {}
                    if parameter['optional'] is False:
                        confapi_methods[method['name']][parameter['field']]['optional'] = 0
                        confapi_methods[method['name']][parameter['field']]['values'] = list()
                        confapi_methods[method['name']][parameter['field']]['default'] = ""
                    else:
                        confapi_methods[method['name']][parameter['field']]['optional'] = 1
                        confapi_methods[method['name']][parameter['field']]['values'] = list()
                        if 'defaultValue' in parameter:
                            confapi_methods[method['name']][parameter['field']]['default'] = parameter['defaultValue']
                        else:
                            confapi_methods[method['name']][parameter['field']]['default'] = ""

                    if 'allowedValues' in parameter:
                        confapi_methods[method['name']][parameter['field']]['type'] = 2
                        for value in parameter['allowedValues']:
                            confapi_methods[method['name']][parameter['field']]['values'].append(value.replace("'", ''))
                    elif parameter['type'] == 'Object':
                        confapi_methods[method['name']][parameter['field']]['type'] = 1
                    else:
                        confapi_methods[method['name']][parameter['field']]['type'] = 0
        #Sort Alphabetically by Parameter of Method
        confapi_methods[method['name']] = collections.OrderedDict(sorted(confapi_methods[method['name']].items()))            
    
    for black_method in black_methods:
        if black_method in confapi_methods:
            confapi_methods.pop(black_method)

    confapi_methods = collections.OrderedDict(sorted(confapi_methods.items()))

    return HttpResponse(json.dumps(confapi_methods), content_type="application/json")
    '''return HttpResponse(json.dumps(response), content_type="application/json")'''
 

janssenlima/confapi/confapi/templates/confapi/configure.html
{% load staticfiles %}
{% include "confapi/header.html" %}
{% include "confapi/navbar.html" %}
<div class="container">
  <form role= "form" action="" method="post">
          <div class="row use_area">
          <div class="divider_bar_top"></div> 
          <hr>
          <h3 class="text-center header_help">Configure</h3><br>

            <div class="col-md-3">
              <input type='text' class='form-control' name='GROUP_OP_SERVICO' placeholder='GROUP_OP_SERVICO (96)'><br>
              <input type='text' class='form-control' name='GROUP_OP_SERVIDOR' placeholder='GROUP_OP_SERVIDOR (98)'><br>
              <input type='text' class='form-control' name='GROUP_OP' placeholder='GROUP_OP (83)'><br>
              <input type='text' class='form-control' name='GROUP_OS_LINUX' placeholder='GROUP_OS_LINUX (15)'><br>
              <input type='text' class='form-control' name='GROUP_DB' placeholder='GROUP_DB (55)'><br>
              <input type='text' class='form-control' name='GROUP_MYSQL' placeholder='GROUP_MYSQL (70)'><br>

            </div>
 
            <div class="col-md-3"> 
              <input type='text' class='form-control' name='GROUP_MONGO' placeholder='GROUP_MONGO (68)'><br>
              <input type='text' class='form-control' name='TEMPLATE_VT' placeholder='TEMPLATE_VT (10069)'><br>
              <input type='text' class='form-control' name='TEMPLATE_MYSQL' placeholder='TEMPLATE_MYSQL (10215)'><br>
              <input type='text' class='form-control' name='TEMPLATE_MONGODB' placeholder='TEMPLATE_MONGODB (18072)'><br>
              <input type='text' class='form-control' name='TEMPLATE_WEBMONITOR' placeholder='TEMPLATE_WEBMONITOR (18981)'><br>
              <input type='text' class='form-control' name='TEMPLATE_HEALTHCHECK' placeholder='TEMPLATE_HEALTHCHECK (18045)'><br>        
            </div>

            <div class="col-md-3">              
              <input type='text' class='form-control' name='PRX_DBFORBIX' placeholder='PRX_DBFORBIX (10121)'><br>
              <input type='text' class='form-control' name='PRX_MONGO' placeholder='PRX_MONGO (10122)'><br>
              <input type='text' class='form-control' name='PRX_DEFAULT' placeholder='PRX_DEFAULT (10106)'><br>
              <input type='text' class='form-control' name='PRX_WEBMONITOR' placeholder='PRX_WEBMONITOR (10109)'><br>
              <input type='text' class='form-control' name='SNMP_PORT' placeholder='SNMP_PORT (161)'><br>
              <input type='text' class='form-control' name='AGENT_PORT' placeholder='AGENT_PORT (10500)'><br>  
            </div>
            
            <div class="col-md-3">              
              <input type='text' class='form-control' name='MONGO_USER' placeholder='MONGO_USER (usr_zabbix)'><br>
              <input type='text' class='form-control' name='MONGO_PASS' placeholder='MONGO_PASS (**********)'><br>
              <input type='text' class='form-control' name='DBFORBIX_USER' placeholder='DBFORBIX_USER (usr_zabbix)'><br>
              <input type='text' class='form-control' name='DBFORBIX_PASS' placeholder='DBFORBIX_PASS (**********)'><br>
              <input type='text' class='form-control' name='MONGO_DEFAULT_PORT' placeholder='MONGO_DEFAULT_PORT (27017)'><br>
              <input type='text' class='form-control' name='MYSQL_DEFAULT_PORT' placeholder='MYSQL_DEFAULT_PORT (3306s)'><br>
            </div>
            <div class='col-md-4 col-md-offset-4'>
              <br><button type='submit' class='btn-lg btn-block btn-primary'>Enviar Parâmetros!</button>
            </div> 
          </div>


  {% csrf_token %}
  </form>
<hr>
</div>
{% include "confapi/footer.html" %}

janssenlima/confapi/confapi/templates/confapi/footer.html
{% load staticfiles %}

<!-- FOOTER -->
  <body>
      <div class="rodape_globo"><footer>
        <p class="pull-right">GLOBO.COM</p>
        <p>&copy; 2015 BackOffice</p>
      </footer></div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'confapi/javascript/jquery.min.js' %}"></script>
    <script src="{% static 'confapi/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'confapi/javascript/docs.min.js' %}"></script>
    <script src="{% static 'confapi/javascript/jqueryxtras.js' %}"></script>

  </body>
</html>

janssenlima/confapi/confapi/templates/confapi/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ConfAPI::GloboCom</title>

    <link rel="shortcut icon" href="{% static 'confapi/icons/favicon.png' %}">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'confapi/bootstrap/css/bootstrap.min.css' %}" />
    <!-- Styles CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'confapi/css/styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'confapi/css/animate.css' %}" />

  </head>

janssenlima/confapi/confapi/templates/confapi/index.html
{% include "confapi/header.html" %}
{% include "confapi/navbar.html" %}
    <!-- Carousel
    ================================================== -->
    
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>

      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img data-src="holder.js/1280x500/auto/#0669de:#0669de/text:Configurar API" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><div class = "globo_font">Configure e Administre a GBIX API</div></h1>
              <p>Aqui você pode alterar as funções da API GBIX de uma forma bem fácil.<br>É possível alterar ou cadastrar novos hostgroups, templates, proxies, macros e mais com apenas alguns cliques!</p>
              <p><a class="btn btn-lg btn-default comingSoon" href="#" role="button" rel="tooltip" data-original-title='Essa funcionalidade será disponibilizada em breve :)' id="red-tooltip"><span class="glyphicon glyphicon-wrench"></span> Configurar a API</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img data-src="holder.js/1280x500/auto/#2D0979:#2D0979/text:Utilizar API!" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><div class = "globo_font">Teste a GBIX API</div></h1>
              <p><br>Utilize e teste a GBIX API de forma super iterativa através do seu browser!</p>
              <p><a class="btn btn-lg btn-success" href="use" role="button"><span class="glyphicon glyphicon-log-in"></span> Utilizar a API</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img data-src="holder.js/1280x500/auto/#555:#5a5a5a/text:Extras" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><div class = "globo_font">Funções Adicionais</div></h1>
              <p>Nesta seção você encontrará funções adicionais não implementadas nativamente pelo Zabbix, como alterações/inclusões/exclusões em massa, filtragens por expressões regulares e muito mais!</p>
              <p><a class="btn btn-lg btn-primary comingSoon" href="#" role="button" rel="tooltip" data-original-title='Essa funcionalidade será disponibilizada em breve :)' id="red-tooltip"><span class="glyphicon glyphicon-plus"></span> Extras</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img data-src="holder.js/1280x500/auto/#812323:#812323/text:Ajuda" alt="Fourth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><div class = "globo_font">Veja a Documentação</div></h1>
              <p><br>Veja aqui a documentação da GBIX API!</p>
              <p><a class="btn btn-lg btn-primary" data-toggle="modal" data-target="#helpModal" data-remote="{% url 'confapi:help' %}" ><span class="glyphicon glyphicon-info-sign"></span> Ajuda</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->
{% include "confapi/footer.html" %}

janssenlima/confapi/confapi/templates/confapi/modal-help.html
<div class="modal fade" id="helpModal" tabindex="-1" aria-labelledby="helpModal" aria-hidden="true">
    <div class="modal-dialog modal-exlg">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
            <h4 class="modal-title"><div class="header_help">GBIX API</div></h4>
            </div>
            <div class="modal-body">
            <iframe width="100%" height="100%" frameborder="0" scrolling="yes" src="{% url 'confapi:help' %}"></iframe>
            </div>
    </div>
  </div>
</div>

janssenlima/confapi/confapi/templates/confapi/navbar.html
{% load staticfiles %}

<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">
        <div class="navbar navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
	      <a href="{% url 'confapi:index' %}"><img src="{% static 'confapi/icons/confapi.png' %}"></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
		<li><a class="comingSoon" href="#" rel="tooltip" data-original-title='Essa funcionalidade será disponibilizada em breve :)' id="ed-tooltip" data-placement="bottom"><span class="glyphicon glyphicon-wrench"></span>Configure</a></li>
                <li><a href="{% url 'confapi:use' %}"><span class="glyphicon glyphicon-log-in"></span>Use</a></li>
                <li><a href="#" class="comingSoon" rel="tooltip" data-original-title='Essa funcionalidade será disponibilizada em breve :)' id"red-tooltip" data-placement="bottom"><span class="glyphicon glyphicon-plus"></span>Extras</a></li>
                <li><a href="#" data-remote="{% url 'confapi:help' %}" data-toggle="modal" data-target="#helpModal"><span class="glyphicon glyphicon-info-sign"></span>Help</a></li>

              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

  {% include "confapi/modal-help.html" %}

janssenlima/confapi/confapi/templates/confapi/use.html
{% load staticfiles %}
{% include "confapi/header.html" %}
{% include "confapi/navbar.html" %}
<div class="container">
	<form role= "form" action="" method="post" id="useForm">


    <div class="row use_area1">
      <hr>
      <div class="col-md-4">
        <h3 class="text-center header_help">1. Informe os Acessos</h3><br>
        <div id='selector-inputbox'>

          <select class="form-control sel selectEndPoint" name="z_endpoint" data-toogle="tooltip" title="Escolha um valor para este campo!" id="red-tooltip"  required>
            <option disabled style='display:none;'>EndPoint</option>
            {% if endpoint_options %}
              {% for endpoint_option in endpoint_options %}
                <option>{{ endpoint_option }}</option>
              {% endfor %}
            {% endif %}
            <option><i>Editar...</i></option>
            {% if z_endpoint %} <option selected style='display:none;'>{{ z_endpoint }}</option> {% endif %}
          </select>
        </div>
        <div class='col-md-offset-5 https-button-area'>
         <label class="btn btn-default btn-sm" data-toggle="buttons"><input type="checkbox" id="https" name="z_https" style='display:none;'>HTTPS</label>
        </div>

        <div class="col-md-6">
          <input type="text" class="form-control" name="z_username" required placeholder="username"  value= "{{ z_username }}"/>
        </div>



        <div class="col-md-6">
          <input type="password" class="form-control" name="z_password" required placeholder="password"  value= "{{ z_password }}">
        </div>
        <br><br>
  

        <hr>

        <h3 class="text-center header_help">2. Selecione a Função</h3>
        <div id='selector-input-function'><select multiple class="form-control   selectFunction" required name="function" style="height:250px; font-size:19px;"></select></div>
      </div>
      <div class="col-md-8">
        <div class="txt">
          {% if post %}
              <br><br><h3 class="text-center header_help">Resposta</h3>
              {% if error %}
                <div class="highlight_error">
                  {{ response }}
                </div>
              {% else %} 
                <div class="highlight">
                  {{ response }}
                </div>
              {% endif %}

          {% endif %}
        </div>
      </div>


    </div>
    <div class="row use_area2">
      
    </div>
 

    
	  {% csrf_token %}
  </form>
  <hr>
</div>
{% include "confapi/footer.html" %}